### ISSUE TITLE
Data storage: the message history per user needs to be stored in a separate file to be saved when user stops a conversation

### ISSUE THREAD

**Issue by jurmy24** [jurmy24/deleted-kids#9]
Currently the chatbot file only stores the conversation history as a list. Eventually we should allow for multiple users to communicate with the API simultaneously and have the data stored in some unstructured database (eg. have two relations: one for users with all the necessary user information, and also one for chat histories connected to the users by a foreign key).

**Comment by Hujon99** [comment]
Yup, that is an important feature in a future stage. But I assume this is not something needed for a first prototype right?

**Comment by jurmy24** [comment]
You're right. For now, like we agreed we should just store the chat history in a separate file so that it persists when the conversation is over.

**Comment by jurmy24** [comment]
Ancient
